# 1. 자연어의 특성
- 자연어가 기계가 처리하도록 하기 위해서는 먼저 자연어를 기계가 이해할 수 있는 언어로 바꾸느느 방법을 알아야 함
- 토큰화 작업의 결과인 단어 사전을 기계가 이해할 수 있는 언어로 표현하는 과정이고, 단어 사전 내 단어 하나를 어떻게 표현할까의 문제로 볼수있음

### 1-1. 단어의 유사성과 모호성
- 단어의 의미는 유사성과 모호성을 가지고 있는데 단어는 겉으로 보이는 형태인 표제어안에 여러가지 의미를 담고 있음

- 사람은 주변 정보에 따라 숨겨진 의미를 파악하고 이해할 수 있으나, 기계는 학습의 부재 또는 잘못된 데이터로 의미를 파악하지 못하는 경우가 있음

- 한 가지 형태의 단어에 여러 의미가 포함되어 생기는 중의성 문제는 자연어 처리에서 매우 중요
  - 동형어 : 형태는 같으나 뜻이 서로 다른 단어(배)
  - 다의어 : 하나의 형태가 여러 의미를 지니면서도 그 의미들이 서로 관련있는 단어(머리)
  - 동의어 : 서로 다른 형태의 단어들이 동일한 의미를 가지는 단어(춘추: 나이)
  - 상의어 : 상위 개념을 가리키는 단어(동물)
  - 하의어 : 하위 개념을 가리키는 단어(강아지)

### 1-2. 언어의 모호성 해소
- 동형어나 다의어처럼 여러 의미를 가지는 단어들이 하나의 형태로 공유, 동의어처럼 하나의 형태를 가지는 단어들이 서로 같은 의미를 공유
- 단어 중의성 해소(WSD) 알고리즘 방법을 통해 단어의 의미를 명확히 함
  - 지식 기반 단어 중의성 해소
    - 컴퓨터가 읽을 수 있는 사전이나 어휘집 등을 바탕으로 단어의 의미를 추론하는 접근 방식
    - 사람이 직접 선별해서 데이터를 넣으므로 노이즈가 적음
    - 구축에 많은 리소스가 필요함
    - 데이터 편향이 생길 수 있음
    - 영어 자연어 처리 분야에서 가장 유명한 WordNet이 있음
  - 지도 학습 기반 단어 중의성 해소
    - 지도 학습은 데이터에 정답이 있다는 의미로, 각종 기계 학습 알고리즘을 통해 단어 의미를 분류해내는 방법
    - WSD라고 하면 보통 단어의 세부 의미가 부착된 코퍼스를 학습 데이터로 사용하여 학습에 쓰이지 않았던 새로운 문장에서 단어 의미를 판별해내는 경우
    - 좋은 성능을 위해서는 질 높은 레이블을 가진 많은 데이터가 필요
    - 데이터가 충분할 경우 일반화된 환경에서도 좋은 성능을 낼 수 있음
  - 비지도 학습 기반 단어 중의성 해소
    - 비지도 학습 WSD는 단어 의미 추론 작업인 WSI를 가리키는 경우가 많음
    - 문장에 등장하는 각 단어의 의미를 사전적인 의미에 연결하지 않고, 세부 의미가 같은 맥락을 군집화하는 데에 초점을 맞춤
    - 대규모 자연어 코퍼스로부터 추가 작업 없이 자동적으로 학습을 수행할 수 있어서 활용 가능성이 높음
    - 사람이 직접 제작한 학습데이터를 사용하지 않기 때문에 성능을 내기 어려움
    


# 2. 임베딩 구축 방법


### 2-1. 임베딩이란
- 자연어처리 작업에서 특징 추출을 통해 자연어를 수치화하는 과정이 필요하고 이런 벡터화의 과정이자 결과
- 토큰화 작업의 목표는 임베딩을 만들기 위한 단어 사전을 구축하는 것

### 2-2. 임베딩의 역할
- 자연어의 의미적인 정보 함축
  - 자연어의 중요한 특징들을 추출하여 벡터로 압축하는 과정
  - 임베딩으로 표현된 문장은 실제 자연어의 주요 정보들을 포함하고 있음
  - 벡터인 만큼 사칙 연상이 가능하여 단어 벡터 간 덫셈/뺼셈을 통해 단어들 사이의 의미적 문법적 관계 도출
  -
- 전이 학습
  - 이미 만들어진 임베딩을 다른 작업을 학습하기 위한 입력값으로 쓰임
  - 품질 좋은 임베딩을 사용할수록 목표로 하는 자연어처리 작업의 학습 속도와 성능이 향상됨
  - 매번 새로운 것을 배울 때 scratch부터 시작한다면 매 학습이 오래 걸림
  - 파인 튜닝 : 학습하는데 임베딩을 초기화하여 사용하면 새로운 작업을 학습함에도 빠르게 학습할 수 있고 성능도 좋아짐연

### 2-3. 단어 출현 빈도에 기반한 임베딩 구축 방법
- 원 핫 인코딩
  - 자연어를 0과 1로 구별하겠다는 인코딩 방법
  - 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 나머지 인덱스에는 0을 부여하는 벡터 표현 방식
  - 예) 단어 사전의 크기가 10,000이라면, 총 10,000개 중 현재 단어를 표현하는 1개의 차원에만 1을, 나머지 9,999개의 차원은 0으로 표현
  - 대부분의 값들이 0인 행렬을 희소행렬이라 하는데, 단어가 늘어날수록 행렬의 크기는 계속 증가하나 증가하는 크기에 비해 표현의 효율성을 떨어짐
  - 단어의 유사도를 표현하지 못함
- Bag of Words
  - 단어들의 순서는 전혀 고려하지 않고 단어들의 출현빈도에 집중하는 자연어 코퍼스 데이터의 사치화 방법
  - 각 단어에 고유한 정수 인덱스를 부여하여 단어 딥합을 생성하고 각 인덱스의 위치에 단어 토큰의 등장횟수를 기록한 벡터 생성
  - 단어 단위의 압축 방식이기 때문에 희소 문제와 단어 순서를 반영하지 못함

TF-IDF
  - 단어의 빈도와 역문서 빈도를 사용하여 문서-단어 행렬 내 각 단어들의 중요한 정도를 가중치로 주는 표현 방법
  - 문서의 유사도를 구하는 작압, 검색 시스템에서 검객 결과의 중요도를 정하는 방법, 문서에대정 단어의 중요도를 구하는 작업 등에서 효과적으로 쓰일 수 있음
  - 단어의 중요도를 고려해도 여전히 단어의 빈도로 판단하는 표현 방식이기 때문에 맥락적 유사도를 반영하지 못함

### 2.4. 단어의 순서
- 통계 기반 언에 모델
  - 단어가 n개 주어졌을 떄 언어 모델은 n개의 단어가 동시에 나타날 확률을 반환
  문장은 어순을 고려하여 여러 단어로 이루어진 단어 시퀀스라고 부르며 n의 단어로 구성된 단어 시퀀스를 확률적으로 표현

- 딥러닝 기반 언어 모델
  - 통계 기반 언어 모델에서는 빈도라는 통계량을 활용하여 확률을 추산했지만, 딥러닝 기반 언어 모델들이 등장한며 입력과 출력사이의 관계를 유연하게 정의할 수 있게 되그 자체로 확률모델로 동작할 수 있음
  - 문장 전체를 다 보고 중간에 있는 단어를 예측하기 떄문에 양방향 학습가능
    - MLM(Masked Languagg modeling)
    - 대표적으로 BERT  모델이 있음
      - 대표적으로 GPT, ELB
    - Next Token Prediction
      - 주어진 단어 시퀀스를 가지고 다음 단어로 어떤단어가 올지 예측


# 3. 텍스트 유사도
- 두 개의 자연어 텍스트가 얼마나 유사한지 나타내는 방법
- 유사도를 정의하거나 판단하는 척도가 주관적이기 때문에, 최대한 정화하는 방법을 찾는 것이 중요함


### 3-1. 유클라디안 거리 기반 유사도
- 두 점 사이의 거리를 측정하는 유클리디안 거리 공식을 사용하여  문서의 유사도를 구하는 방법으로 거리가 가까울수록 유사도가 높다고 판단
- 자연어 처리 분야뿐 아닐라 다른 알고리즘 분야에도 범용적으로 사용되는 거리 측정 기법

### 3-2. 맨하탄 거리 기반 유사도
- 맨하탄 거리를 사용하여 문서의 유사도를 구하는 방법
- 유클리드 거리 공식과 유사하나 각 차원의 차를 곱해서 사용하는 대신 절대값을 바로 합산함
- 유클리드 거리 공식보다 값이 크거나 같음
- 다차원 공간 상에서 두 좌표 간 최단거리를 구하는 방법이 아니다 보니 특별한 상황이 아니면 잘 사용되지 않음

### 3-3. 코사인 유사도
- 두 개의 벡터값에서 코사인 각도를 이용하여 구할 수 있는 두 벡터의 유사도를 의미
- 두 벡터의 방향이 완전히 동일한 경우는 1의 값을 가지며, 90도의 각을 이루면 0,180도로 반대의 방향을 가지면 -1의 값을 가짐
- -1이상 1이하의 값을 가지며, 값이 1에 가까울수록 유사하는 것을 의미
- 두 벡터가 가리키는 방향이 얼마나 유사한가를 의미하기 때문에 자연어 내 유사도 계산에 더 적합함

### 3-4. 자카드 유사도
- 두 문장을 각각 단어의 집합으로 만든 뒤 두 집합을 통해 유사도를 측정하는 방식
- 수치화된 벡터 없이 단어 집합만으로 계산 할 수 있음
- 두 집합의 교집합인 공통된 단어의 개수를 두 집합의 합집합을 전체 단어의 개수로 나누는 것
- 전체 합집합 중 공통의 단어의 개수에 따라 0과 1사이의 값을 가지며, 1에 가까울수록 유사도가 높음

# 4. 유사도 측정 실습

In [2]:
sen_1 = '오늘 점심에 배가 너무 고파서 밥을 너무 많이 먹었다.'
sen_2 = '오늘 점심에 배가 고파서 밥을 많이 먹었따.'
sen_3 = '오늘 배가 너무 고파서 점심에 밥을 너무 많이 먹었다.'
sen_4 = '오늘 점심에 배고 고파서 버스를 많이 먹었다.'
sen_5 = '어제 저녁에 밥을 너무 많이 먹었더니 배가 부르다.'
sen_6 = '이따가 오후 7시에 출발하는 비행기가 3시간 연착 되었다고 하네요.'

In [3]:
training_documents = [sen_1, sen_2, sen_3, sen_4, sen_5, sen_6]

In [4]:
for text in training_documents:
  print(text)

오늘 점심에 배가 너무 고파서 밥을 너무 많이 먹었다.
오늘 점심에 배가 고파서 밥을 많이 먹었따.
오늘 배가 너무 고파서 점심에 밥을 너무 많이 먹었다.
오늘 점심에 배고 고파서 버스를 많이 먹었다.
어제 저녁에 밥을 너무 많이 먹었더니 배가 부르다.
이따가 오후 7시에 출발하는 비행기가 3시간 연착 되었다고 하네요.


In [5]:
# Bag of Words 기반 문서-단어 행렬을 활용한 문장 간 유사도 측정
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
vectorizer = CountVectorizer()
vectorizer.fit(training_documents)

CountVectorizer()

In [7]:
word_idx = vectorizer.vocabulary_
word_idx

{'오늘': 17,
 '점심에': 21,
 '배가': 10,
 '너무': 3,
 '고파서': 2,
 '밥을': 9,
 '많이': 5,
 '먹었다': 6,
 '먹었따': 8,
 '배고': 11,
 '버스를': 12,
 '어제': 15,
 '저녁에': 20,
 '먹었더니': 7,
 '부르다': 13,
 '이따가': 19,
 '오후': 18,
 '7시에': 1,
 '출발하는': 22,
 '비행기가': 14,
 '3시간': 0,
 '연착': 16,
 '되었다고': 4,
 '하네요': 23}

In [8]:
# word_dix 를 dix 순서대로 정렬

for key , idx in sorted(word_idx.items()):
  print(f'{key} : {idx}')


3시간 : 0
7시에 : 1
고파서 : 2
너무 : 3
되었다고 : 4
많이 : 5
먹었다 : 6
먹었더니 : 7
먹었따 : 8
밥을 : 9
배가 : 10
배고 : 11
버스를 : 12
부르다 : 13
비행기가 : 14
어제 : 15
연착 : 16
오늘 : 17
오후 : 18
이따가 : 19
저녁에 : 20
점심에 : 21
출발하는 : 22
하네요 : 23


In [9]:
# word_idx에 따라 dataframe을 생성
# 컬럼 : key, 인덱스 : 문장idx, 값 : 빈도수

import pandas as pd

In [10]:
result = []
vocab = list(word_idx.keys())

for i in range(len(training_documents)):
  result.append([])
  d = training_documents[i]
  for j in range(len(vocab)):
    target = vocab[j]
    result[-1].append(d.count(target))

tf = pd.DataFrame(result, columns=vocab)
tf

오늘  점심에  배가  너무  고파서  밥을  많이  먹었다  먹었따  배고  ...  부르다  이따가  오후  7시에  출발하는  \
0   1    1   1   2    1   1   1    1    0   0  ...    0    0   0    0     0   
1   1    1   1   0    1   1   1    0    1   0  ...    0    0   0    0     0   
2   1    1   1   2    1   1   1    1    0   0  ...    0    0   0    0     0   
3   1    1   0   0    1   0   1    1    0   1  ...    0    0   0    0     0   
4   0    0   1   1    0   1   1    0    0   0  ...    1    0   0    0     0   
5   0    0   0   0    0   0   0    0    0   0  ...    0    1   1    1     1   

   비행기가  3시간  연착  되었다고  하네요  
0     0    0   0     0    0  
1     0    0   0     0    0  
2     0    0   0     0    0  
3     0    0   0     0    0  
4     0    0   0     0    0  
5     1    1   1     1    1  

[6 rows x 24 columns]

In [11]:
# 유사도를 측정할 문장들을 문장-단어 행렬 기반 임베딩으로 변환
vector_sen_1 = vectorizer.transform([sen_1]).toarray()[0]
vector_sen_1

array([0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0])

In [12]:
vector_sen_1 = vectorizer.transform([sen_1]).toarray()[0]
vector_sen_2 = vectorizer.transform([sen_2]).toarray()[0]
vector_sen_3 = vectorizer.transform([sen_3]).toarray()[0]
vector_sen_4 = vectorizer.transform([sen_4]).toarray()[0]
vector_sen_5 = vectorizer.transform([sen_5]).toarray()[0]
vector_sen_6 = vectorizer.transform([sen_6]).toarray()[0]

In [13]:
print(vector_sen_1)
print(vector_sen_2)
print(vector_sen_3)
print(vector_sen_4)
print(vector_sen_5)
print(vector_sen_6)

[0 0 1 2 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 1 2 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0]
[0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1]


In [14]:
# 코사인 기반 유사도 계산
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [15]:
def cos_sim(A,B):
  return dot(A, B) / (norm(A) * norm(B))

```
sen_1 = '오늘 점심에 배가 너무 고파서 밥을 너무 많이 먹었다.'
sen_2 = '오늘 점심에 배가 고파서 밥을 많이 먹었따.'
sen_3 = '오늘 배가 너무 고파서 점심에 밥을 너무 많이 먹었다.'
sen_4 = '오늘 점심에 배고 고파서 버스를 많이 먹었다.'
sen_5 = '어제 저녁에 밥을 너무 많이 먹었더니 배가 부르다.'
sen_6 = '이따가 오후 7시에 출발하는 비행기가 3시간 연착 되었다고 하네요.'

```

- sen_1, sen_2 : 의미가 유사한 문장 간 유사도 계산(조사 생략)
- sen_1, sen_3 : 의미가 유사한 문장 간 유사도 계산(순서 변경)
- sen_2, sen_4 : 문장 내 단어를 임의의 단어로 치환한 문장과 원 문장 간 유사도 계산
- sen_1, sen_5 : 의미는 다르지만 비슷한 주제를 가지는 문장 간 유사도 계산
- sen_1, sen_6 : 의미가 서로 다른 문장 간 유사도 계산

In [16]:
print(f'sen_1, sen_2 : {cos_sim(vector_sen_1, vector_sen_2)}')
print(f'sen_1, sen_3 : {cos_sim(vector_sen_1, vector_sen_3)}')
print(f'sen_2, sen_4 : {cos_sim(vector_sen_2, vector_sen_4)}')
print(f'sen_1, sen_5 : {cos_sim(vector_sen_1, vector_sen_5)}')
print(f'sen_1, sen_6 : {cos_sim(vector_sen_1, vector_sen_6)}')

sen_1, sen_2 : 0.6837634587578276
sen_1, sen_3 : 1.0
sen_2, sen_4 : 0.5714285714285714
sen_1, sen_5 : 0.5330017908890261
sen_1, sen_6 : 0.0


In [17]:
# TF-IDF 기반 문서-단어 행렬을 활용한 문장 간 유사도 측정
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
tfidfv = TfidfVectorizer().fit(training_documents)

In [19]:
for key, idx in sorted(tfidfv.vocabulary_.items()):
  print(f'{key} : {idx}')

3시간 : 0
7시에 : 1
고파서 : 2
너무 : 3
되었다고 : 4
많이 : 5
먹었다 : 6
먹었더니 : 7
먹었따 : 8
밥을 : 9
배가 : 10
배고 : 11
버스를 : 12
부르다 : 13
비행기가 : 14
어제 : 15
연착 : 16
오늘 : 17
오후 : 18
이따가 : 19
저녁에 : 20
점심에 : 21
출발하는 : 22
하네요 : 23


In [20]:
tf_idf = tfidfv.transform(training_documents).toarray()
print(tf_idf)

[[0.         0.         0.28222473 0.65869253 0.         0.24372363
  0.32934627 0.         0.         0.28222473 0.28222473 0.
  0.         0.         0.         0.         0.         0.28222473
  0.         0.         0.         0.28222473 0.         0.        ]
 [0.         0.         0.34125457 0.         0.         0.29470062
  0.         0.         0.57522007 0.34125457 0.34125457 0.
  0.         0.         0.         0.         0.         0.34125457
  0.         0.         0.         0.34125457 0.         0.        ]
 [0.         0.         0.28222473 0.65869253 0.         0.24372363
  0.32934627 0.         0.         0.28222473 0.28222473 0.
  0.         0.         0.         0.         0.         0.28222473
  0.         0.         0.         0.28222473 0.         0.        ]
 [0.         0.         0.30442989 0.         0.         0.26289956
  0.35525891 0.         0.         0.         0.         0.51314825
  0.51314825 0.         0.         0.         0.         0.30442989
 

In [21]:
# TF-IDF 행렬에서 얻어지는 유사도의 값을 0 ~ 1로 스케일링하기 위해 L1정규화를 진행
def l1_normalize(v):
  norm = np.sum(v)
  return v / norm

In [22]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix_l1 = tfidf_vectorizer.fit_transform(training_documents)
tfidf_norm_l1 = l1_normalize(tfidf_matrix_l1)
tfidf_norm_l1

<6x24 sparse matrix of type '<class 'numpy.float64'>'
	with 47 stored elements in Compressed Sparse Row format>

In [23]:
tf_sen_1 = tfidf_norm_l1[0:1]
tf_sen_2 = tfidf_norm_l1[1:2]
tf_sen_3 = tfidf_norm_l1[2:3]
tf_sen_4 = tfidf_norm_l1[3:4]
tf_sen_5 = tfidf_norm_l1[4:5]
tf_sen_6 = tfidf_norm_l1[5:6]

In [24]:
tf_sen_1.toarray()

array([[0.        , 0.        , 0.01746606, 0.04076455, 0.        ,
        0.01508334, 0.02038227, 0.        , 0.        , 0.01746606,
        0.01746606, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01746606, 0.        , 0.        ,
        0.        , 0.01746606, 0.        , 0.        ]])

In [25]:
# 유클리디안 거리 기반 유사도 측정
from sklearn.metrics.pairwise import euclidean_distances

In [26]:
euclidean_distances(tf_sen_1, tf_sen_2)

array([[0.05849046]])

In [27]:
def euclidean_distances_value(vec_1,vec_2):
  return round(euclidean_distances(vec_1, vec_2)[0][0],3)

In [28]:
print(f'sen_1, sen_2 : {euclidean_distances_value(tf_sen_1, tf_sen_2)}')
print(f'sen_1, sen_3 : {euclidean_distances_value(tf_sen_1, tf_sen_3)}')
print(f'sen_2, sen_4 : {euclidean_distances_value(tf_sen_2, tf_sen_4)}')
print(f'sen_1, sen_5 : {euclidean_distances_value(tf_sen_1, tf_sen_5)}')
print(f'sen_1, sen_6 : {euclidean_distances_value(tf_sen_1, tf_sen_6)}')

sen_1, sen_2 : 0.058
sen_1, sen_3 : 0.0
sen_2, sen_4 : 0.068
sen_1, sen_5 : 0.068
sen_1, sen_6 : 0.088


In [1]:
from sklearn.metrics.pairwise import manhattan_distances, cosine_similarity

In [40]:
# 맨해튼 거리 기반 유사도 측정
# 소수 2자리까지 유사도 표현
manhattan_distances(tf_sen_1, tf_sen_2)

def manhattan_distance_value(vec_1, vec_2):
  return round(manhattan_distances(vec_1,vec_2)[0][0],2)

print(f's1, s2 : {manhattan_distance_value(tf_sen_1,tf_sen_2)}')
print(f's1, s3 : {manhattan_distance_value(tf_sen_1,tf_sen_3)}')
print(f's2, s4 : {manhattan_distance_value(tf_sen_2,tf_sen_4)}')
print(f's1, s5 : {manhattan_distance_value(tf_sen_1,tf_sen_5)}')
print(f's1, s6 : {manhattan_distance_value(tf_sen_1,tf_sen_6)}')



s1, s2 : 0.12
s1, s3 : 0.0
s2, s4 : 0.17
s1, s5 : 0.21
s1, s6 : 0.35


In [41]:
# 코사인 유사도 측정


def cosine_similarity_value(vec_1, vec_2):
    return round(cosine_similarity(vec_1, vec_2)[0][0], 2)

print(f's1, s2 : {cosine_similarity_value(tf_sen_1,tf_sen_2)}')
print(f's1, s3 : {cosine_similarity_value(tf_sen_1,tf_sen_3)}')
print(f's2, s4 : {cosine_similarity_value(tf_sen_2,tf_sen_4)}')
print(f's1, s5 : {cosine_similarity_value(tf_sen_1,tf_sen_5)}')
print(f's1, s6 : {cosine_similarity_value(tf_sen_1,tf_sen_6)}')

s1, s2 : 0.55
s1, s3 : 1.0
s2, s4 : 0.39
s1, s5 : 0.39
s1, s6 : 0.0


In [42]:
!pip install transformers

In [43]:
from transformers import AutoModel, AutoTokenizer , BertTokenizer

In [45]:
MODEL_NAME = 'bert-base-multilingual-cased'

model = AutoModel.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

In [46]:
bert_sen_1 = tokenizer(sen_1, return_tensors='pt')  # 파이토치 텐서로 리턴시켜줌
bert_sen_2 = tokenizer(sen_2, return_tensors='pt')
bert_sen_3 = tokenizer(sen_3, return_tensors='pt')
bert_sen_4 = tokenizer(sen_4, return_tensors='pt')
bert_sen_5 = tokenizer(sen_5, return_tensors='pt')
bert_sen_6 = tokenizer(sen_6, return_tensors='pt')

In [47]:
bert_sen_1

{'input_ids': tensor([[   101,   9580, 118762,   9668,  71013,  10530,   9330,  11287,   9004,
          32537,   8888,  46150,  12424,   9327,  10622,   9004,  32537,  47058,
           9266,  17706,    119,    102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [48]:
sen_1_outputs = model(**bert_sen_1)
# pooler_output : BERT 모델에서 나오는 마지막 레이어의 출력, 입력 텍스트에 대한  최종
sen_1_pooler_output = sen_1_outputs.pooler_output

sen_2_outputs = model(**bert_sen_2)
sen_2_pooler_output = sen_2_outputs.pooler_output

sen_3_outputs = model(**bert_sen_3)
sen_3_pooler_output = sen_3_outputs.pooler_output

sen_4_outputs = model(**bert_sen_4)
sen_4_pooler_output = sen_4_outputs.pooler_output

sen_5_outputs = model(**bert_sen_5)
sen_5_pooler_output = sen_5_outputs.pooler_output

sen_6_outputs = model(**bert_sen_6)
sen_6_pooler_output = sen_6_outputs.pooler_output

In [49]:
from torch import nn

In [51]:
cos_sim = nn.CosineSimilarity(dim=1, eps=1e-6)
cos_sim

CosineSimilarity()

In [52]:
print(f's1, s2 : {cos_sim(sen_1_pooler_output, sen_2_pooler_output)}')
print(f's1, s3 : {cos_sim(sen_1_pooler_output, sen_3_pooler_output)}')
print(f's2, s4 : {cos_sim(sen_2_pooler_output, sen_4_pooler_output)}')
print(f's1, s5 : {cos_sim(sen_1_pooler_output, sen_5_pooler_output)}')
print(f's1, s6 : {cos_sim(sen_1_pooler_output, sen_6_pooler_output)}')

s1, s2 : tensor([0.9916], grad_fn=<SumBackward1>)
s1, s3 : tensor([0.9972], grad_fn=<SumBackward1>)
s2, s4 : tensor([0.9672], grad_fn=<SumBackward1>)
s1, s5 : tensor([0.9744], grad_fn=<SumBackward1>)
s1, s6 : tensor([0.9533], grad_fn=<SumBackward1>)
